#!/bin/bash

#BSUB -J filter_caveman_output 
#BSUB -o logs/filter_caveman.out
#BSUB -e logs/filter_caveman.err
#BSUB -W 02:00
#BSUB -n 2
#BSUB -R "span[hosts=1] select[mem>2000] rusage[mem=2000]" -M 2000
#BSUB -N
#BSUB -B


# This script filters the output vcf files generated by the CaVEMan variant calling pipeline. 
# First, it filters out variants that did not 'PASS' CaVEMan's intrinsic filters. 
# Then, the script discards the NORMAL sample and sex chromosomes / unmapped contigs and applies 
# filters for 10<=DP<=100, ASRD>=0.94 (read-adjusted median alignment score), CLPM==0.0 
# (excludes variants from soft-clipped reads) and PM=>0.300 (VAF of equal/more than 0.3, indicates 
# that heterozygous mutations stem from the original single cell in clonal expansion samples, 
# see https://www.nature.com/articles/nprot.2017.111). 


out_dir="/.../"

# load required modules 
module load htslib/1.15.1
module load bcftools/1.16
module load R/4.3.0
 
# get vcf.gz input files 
readarray -t unfiltered_vcfs < <(find /path/to/unfiltered/caveman_output/  -maxdepth 2 | grep "\.flagged\.muts\.vcf\.gz$")

for vcf in ${unfiltered_vcfs[@]}; do
	echo $vcf
	file_name=$(echo $vcf | grep -oP "sample_control.*(?=\.flagged\.muts)")


	# FILTERING ----------------------------------------------------------------------------------------------------------
	output="${out_dir}${file_name}_filtered.vcf.gz"

	# apply filtering and save as .vcf.gz file
	bcftools view -s TUMOUR -r 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19 $vcf | bcftools filter -i "FILTER='PASS'" | 
	bcftools filter -i "10<=DP & ASRD>=0.94 & CLPM==0.0 & PM>=0.300" | bcftools filter -i "DP<=100" --output $output --output-type z

	# index the filtered vcf file 
	bcftools index --tbi $output
	
	# FOR NORMALIZATION PURPOSES: EXPORT FILES CONTAINING THE EXCLUDED SITES ---------------------------------------------
	# uncallable positions due to quality concerns in the PASS filter or ASRD/CLPM 
	# (simple repeats, centromeric repeats and 10> depth >100 should be excluded based on the whole genome, potentially also base quality and mapping quality)  
	bcftools filter -i "FILTER~'DTH' | FILTER~'RP' | FILTER~'PT' | FILTER~'MQ' | FILTER~'PH' | FILTER~'GI' | FILTER~'SE'| FILTER~'MNP' | ASRD<0.94 | CLPM!=0.0" $vcf\
	--output "${norm_dir}/${file_name}_uncallable.vcf.gz" --output-type z  

done   
