# ============================================================
# 3_MaskBuilding.R
# Cross-species NanoSeq: SNP mask pipeline — Step 3
# Build SNP and noise masks from pileup and coverage data
#
# Author: Adrian Baez-Ortega, 2023
# Adapted for use in: HSC mutagenesis study (Cagan Lab)
#
# Usage: Rscript 3_MaskBuilding.R <species> <path_to_ref.fa> <chr_index>
#
# Arguments:
#   1. Species name (must match output directory name)
#   2. Path to reference FASTA
#   3. Target chromosome index (integer)
#
# Input files (generated by Steps 1 and 2):
#   output/<species>/<sample>.covhist.txt
#   output/<species>/<sample>.pileup.vcf.gz
#
# Output:
#   output/<species>/SNP+NOISE.NV2.SeenNV1.<species>_chr<N>.bed
#   output/<species>/SNP.POS.<species>_chr<N>.txt
#   output/<date>_SNP_Hist_<species>.pdf  (coverage/VAF histograms, chr1 only)
#
# Dependencies: stringr, Biostrings, GenomicRanges
# ============================================================

ARGS     = commandArgs(TRUE)
SPECIES  = ARGS[1]
REF      = ARGS[2]
CHR.IDX  = as.integer(ARGS[3])

# Input/output path templates
COV.PATH     = "output/${SPEC}/${NAME}.covhist.txt"
VCF.PATH     = "output/${SPEC}/${NAME}.pileup.vcf.gz"
MASK.PATH    = "output/${SPEC}/SNP+NOISE.NV2.SeenNV1.${SPEC}_chr${CHR}.bed"
SNP.POS.PATH = "output/${SPEC}/SNP.POS.${SPEC}_chr${CHR}.txt"
HIST.PATH    = paste0("output/", Sys.Date(), "_SNP_Hist_${SPEC}.pdf")

# Function: apply multiple gsub replacements sequentially
multi.gsub = function(patterns, replacements, x, ...) {
    stopifnot(length(patterns) == length(replacements))
    for (i in seq_along(patterns)) {
        x = gsub(patterns[i], replacements[i], x, fixed=TRUE, ...)
    }
    x
}

# Load packages
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(Biostrings))
suppressPackageStartupMessages(library(GenomicRanges))

# Get chromosome names from reference FASTA index
chr.names = sapply(strsplit(names(fasta.seqlengths(REF)), " "), `[`, 1)
cat("\nProcessing chromosome:", chr.names[CHR.IDX], "\n")

# Open output PDF for coverage and VAF histograms (chr1 only)
if (CHR.IDX == 1) {
    pdf(gsub("${SPEC}", SPECIES, HIST.PATH, fixed=TRUE), 18, 6)
    par(mfrow=c(1, 2), mar=c(5, 5, 4, 1))
}

# Get sample IDs from pileup output files
sample.ids = gsub(".pileup.vcf.gz", "", list.files(file.path("output", SPECIES), "pileup"))

# Initialise containers for SNP and noise variant sets
snp.all = noise.all = GRanges()
seen.prev = NULL

for (sample.id in sample.ids) {
    cat("\n", sample.id, " (", SPECIES, ")\n", sep="")

    # ── COVERAGE ──────────────────────────────────────────────────────────────
    # Read coverage histogram and calculate percentiles
    cov = read.table(
        multi.gsub(c("${SPEC}", "${NAME}"), c(SPECIES, sample.id), COV.PATH),
        sep="\t", as.is=TRUE,
        col.names=c("name", "cov", "count", "total", "frac")
    )
    cov$frac.non0     = cov$count / (cov$total - cov$count[1])
    cov$frac.non0[1]  = 0
    cov$cum.frac      = sapply(1:nrow(cov), function(i) sum(cov$frac[i:nrow(cov)]))
    cov$cum.frac.non0 = sapply(1:nrow(cov), function(i) sum(cov$frac.non0[i:nrow(cov)]))

    cov.median       = cov[which(cov$cum.frac < 0.5)[1] - 1, 2]
    cov.median.non0  = cov[which(cov$cum.frac.non0 < 0.5)[1] - 1, 2]
    cov.95pctl.non0  = cov[which(cov$cum.frac.non0 < 0.05)[1] - 1, 2]
    cov.98pctl.non0  = cov[which(cov$cum.frac.non0 < 0.02)[1] - 1, 2]
    cov.99pctl.non0  = cov[which(cov$cum.frac.non0 < 0.01)[1] - 1, 2]

    cat("95th coverage (>0) percentile =", cov.95pctl.non0, "\n")
    cat("98th coverage (>0) percentile =", cov.98pctl.non0, "\n")
    cat("99th coverage (>0) percentile =", cov.99pctl.non0, "\n")

    # ── VARIANT CALLING ───────────────────────────────────────────────────────
    # Read pileup VCF and calculate NR, NV, VAF per site
    cnames = c("CHROM","POS","ID","REF","ALT","QUAL","FILTER","INFO","FORMAT","SAMPLE")
    vars = read.table(
        gzfile(multi.gsub(c("${SPEC}", "${NAME}"), c(SPECIES, sample.id), VCF.PATH)),
        sep="\t", as.is=TRUE, col.names=cnames
    )[, c(1:2, 4:5, 8)]

    vars = vars[!is.na(vars$REF) & !is.na(vars$ALT), ]

    if (!any(vars$CHROM == chr.names[CHR.IDX])) {
        cat("No variants found in this chromosome!\n")
        next
    }

    vars = vars[vars$CHROM == chr.names[CHR.IDX], ]
    vars$ALT = gsub(",.*", "", vars$ALT)

    counts = t(sapply(str_split(vars$INFO, ";"), function(x) {
        y = str_split_fixed(x[startsWith(x, "I16=")], "=", 2)[, 2]
        as.integer(str_split_fixed(y, ",", 16)[, 1:4])
    }))

    vars$END = vars$POS - 1 + apply(cbind(nchar(vars$REF), nchar(vars$ALT)), 1, max)
    vars$STR = paste0(vars$CHROM, ":", vars$POS, ":", vars$REF, ":", vars$ALT)
    vars$NR  = rowSums(counts)
    vars$NV  = rowSums(counts[, 3:4, drop=FALSE])
    vars$VAF = ifelse(vars$NR == 0, 0, vars$NV / vars$NR)

    # ── MASKING THRESHOLDS ────────────────────────────────────────────────────
    # SNP:   1-bp substitutions with NR ≥10, NR ≤98th percentile, NV ≥3, VAF ≥0.2
    # NOISE: NV ≥2 and VAF ≥0.01 (includes all SNPs),
    #        OR NV ≥1 and VAF ≥0.01 seen in ≥2 samples
    MIN.NR.SNP    = 10
    MAX.NR.SNP    = cov.98pctl.non0
    MIN.NV.SNP    = 3
    MIN.VAF.SNP   = 0.2
    MIN.NV.SEEN   = 1
    MIN.VAF.SEEN  = 0.01
    MIN.NV.NOISE  = 2
    MIN.VAF.NOISE = 0.01

    seen.idx  = vars$NV >= MIN.NV.SEEN & vars$VAF >= MIN.VAF.SEEN
    noise.idx = (vars$NV >= MIN.NV.NOISE & vars$VAF >= MIN.VAF.NOISE) |
                (seen.idx & vars$STR %in% seen.prev)
    snp.idx   = nchar(vars$REF) == 1 & nchar(vars$ALT) == 1 &
                vars$NR >= MIN.NR.SNP & vars$NR <= MAX.NR.SNP &
                vars$NV >= MIN.NV.SNP & vars$VAF >= MIN.VAF.SNP

    # Update 'seen' list: add newly seen variants not yet in NOISE;
    # remove variants now in NOISE to save memory
    seen.prev = c(
        seen.prev[!(seen.prev %in% vars$STR[noise.idx])],
        vars$STR[seen.idx & !noise.idx]
    )

    # Accumulate SNP and NOISE variant sets across samples
    if (any(snp.idx)) {
        snp.all = union(snp.all,
                        makeGRangesFromDataFrame(vars[snp.idx, ], start.field="POS"))
    }
    if (any(noise.idx)) {
        noise.all = union(noise.all,
                          makeGRangesFromDataFrame(vars[noise.idx, ], start.field="POS"))
    }

    cat("Total in SNP:  ", prettyNum(length(snp.all),   big.mark=","),
        "\nTotal in NOISE:", prettyNum(length(noise.all), big.mark=","), "\n")

    # ── DIAGNOSTICS ───────────────────────────────────────────────────────────
    # Plot coverage and VAF histograms for chr1 only
    if (CHR.IDX == 1) {
        MAX.COV = 100
        MAX.FRC = 0.1
        bars = barplot(cov[1:(MAX.COV+1), 5], plot=FALSE)
        barplot(cov[1:(MAX.COV+1), 5],
                col="dodgerblue4", border="white",
                xlim=c(0, rev(bars)[1]), ylim=c(0, MAX.FRC), xpd=FALSE,
                xlab="Coverage", ylab="Genome fraction",
                main=paste0("Coverage in ", sample.id, " (", SPECIES, ")"))
        text(0, 0.102,
             labels=round(cov[1, 5], 2),
             col="dodgerblue4", adj=0, font=2, xpd=NA)
        abline(v=c(MIN.NR.SNP, MAX.NR.SNP))
        legend("topright", legend=c(
            paste("Median (all) =",         cov.median),
            paste("Median (>0) =",          cov.median.non0),
            paste("95th percentile (>0) =", cov.95pctl.non0),
            paste("98th percentile (>0) =", cov.98pctl.non0),
            paste("99th percentile (>0) =", cov.99pctl.non0)
        ))
        axis(1, at=bars[seq(1, MAX.COV+1, 25)],
             labels=cov[seq(1, MAX.COV+1, 25), 2])
        hist(vars$VAF, breaks=seq(0, 1, 0.01),
             col="darkgreen", border="white",
             xlim=c(0, 1), xlab="VAF", ylab="Frequency",
             main=paste0("VAF in ", sample.id, " (", SPECIES, ") (chr1 only)"))
        abline(v=c(MIN.VAF.SNP, MIN.VAF.NOISE))
    }

    rm(vars, counts)
    invisible(gc())
}

if (CHR.IDX == 1) {
    invisible(dev.off())
}

# ── OUTPUT ────────────────────────────────────────────────────────────────────
# Write NOISE+SNP set as BED mask (0-based coordinates)
# Write SNP positions as TSV
cat("\nSaving SNP+NOISE mask and SNP positions...\n")

start(noise.all) = start(noise.all) - 1  # convert to 0-based BED coordinates

write.table(
    as.data.frame(noise.all)[, 1:3],
    sep="\t", quote=FALSE, row.names=FALSE, col.names=FALSE,
    file=multi.gsub(c("${SPEC}", "${CHR}"), c(SPECIES, chr.names[CHR.IDX]), MASK.PATH)
)

write.table(
    as.data.frame(snp.all)[, 1:2],
    sep="\t", quote=FALSE, row.names=FALSE, col.names=FALSE,
    file=multi.gsub(c("${SPEC}", "${CHR}"), c(SPECIES, chr.names[CHR.IDX]), SNP.POS.PATH)
)

cat("\nDone\n")
